language: node_js
node_js:
  - lts/*
cache:
  yarn: true

before_install:
  - export PATH=$PATH:`yarn global bin` # temporary until TravisCI fixes issue
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
script: yarn test || echo "Why are my tests not working!?"
after_script: greenkeeper-lockfile-upload

before_deploy: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "dustinschau.com"
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    branch: master
