language: node_js
node_js:
- stable
cache:
  yarn: true

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload

before_deploy: yarn build
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
